/* eslint-disable */
// AUTO-GENERATED by scripts/generate-game-guides.mjs — do not edit manually
import type { GameGuide } from './types';

export const GAME_GUIDES: GameGuide[] = [
];

export const GUIDE_GAME_GROUPS: Record<string, string> = {};
